spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: ${POSTGRES_USER:pguser}
    driver-class-name: org.postgresql.Driver

jwt:
  secret-file: ../secrets/jwt_secret.txt